/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  DataAndJobHandlingApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierDataHandlingCustom } from "./client-custom";

export class VisierDataHandling extends VisierDataHandlingCustom {
  readonly dataAndJobHandling: DataAndJobHandlingApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.dataAndJobHandling = new DataAndJobHandlingApi(configuration);
  }

}
