/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Connector } from './connector';

/**
 * 
 * @export
 * @interface AssignConnectorCredentialRequest
 */
export interface AssignConnectorCredentialRequest {
    /**
     * A list of objects representing the data connectors to be assigned with credentials.
     * @type {Array<Connector>}
     * @memberof AssignConnectorCredentialRequest
     */
    'connectors'?: Array<Connector>;
}

