/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssignConnectorWithCredentialsResponseDTO } from './assign-connector-with-credentials-response-dto';

/**
 * 
 * @export
 * @interface AssignConnectorCredentialsByTenantResponseDTO
 */
export interface AssignConnectorCredentialsByTenantResponseDTO {
    /**
     * The unique identifier associated with the tenant.
     * @type {string}
     * @memberof AssignConnectorCredentialsByTenantResponseDTO
     */
    'tenantCode'?: string;
    /**
     * A list of objects representing the assigned credentials and connectors.
     * @type {Array<AssignConnectorWithCredentialsResponseDTO>}
     * @memberof AssignConnectorCredentialsByTenantResponseDTO
     */
    'connectors'?: Array<AssignConnectorWithCredentialsResponseDTO>;
    /**
     * The state of the credential assignment. Valid values are Succeed or Failed.
     * @type {string}
     * @memberof AssignConnectorCredentialsByTenantResponseDTO
     */
    'status'?: AssignConnectorCredentialsByTenantResponseDTOStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AssignConnectorCredentialsByTenantResponseDTO
     */
    'message'?: string;
}

type AssignConnectorCredentialsByTenantResponseDTOStatusEnum = 'Unknown' | 'Succeed' | 'Failed'


