/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssignedCredentialInfoResponseDTO } from './assigned-credential-info-response-dto';
import { ConnectorInfoResponseDTO } from './connector-info-response-dto';

/**
 * 
 * @export
 * @interface AssignConnectorWithCredentialsResponseDTO
 */
export interface AssignConnectorWithCredentialsResponseDTO {
    /**
     * The data connector that was assigned a connector credential.
     * @type {ConnectorInfoResponseDTO}
     * @memberof AssignConnectorWithCredentialsResponseDTO
     */
    'connector'?: ConnectorInfoResponseDTO;
    /**
     * A connector credential that was assigned to a data connector
     * @type {AssignedCredentialInfoResponseDTO}
     * @memberof AssignConnectorWithCredentialsResponseDTO
     */
    'credential'?: AssignedCredentialInfoResponseDTO;
}

