/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AssignedCredentialInfoResponseDTO
 */
export interface AssignedCredentialInfoResponseDTO {
    /**
     * The unique identifier associated with the user.
     * @type {string}
     * @memberof AssignedCredentialInfoResponseDTO
     */
    'credentialId'?: string;
    /**
     * The user\'s username. This is typically the user\'s email, such as john@visier.com.
     * @type {string}
     * @memberof AssignedCredentialInfoResponseDTO
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssignedCredentialInfoResponseDTO
     */
    'message'?: string;
}

