/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssignConnectorCredentialsByTenantResponseDTO } from './assign-connector-credentials-by-tenant-response-dto';

/**
 * 
 * @export
 * @interface AssignConnectorCredentialsResponseDTO
 */
export interface AssignConnectorCredentialsResponseDTO {
    /**
     * A list of objects representing the tenants and data connectors that were assigned connector credentials.
     * @type {Array<AssignConnectorCredentialsByTenantResponseDTO>}
     * @memberof AssignConnectorCredentialsResponseDTO
     */
    'tenants'?: Array<AssignConnectorCredentialsByTenantResponseDTO>;
}

