/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BasicS3AuthParamsDTO
 */
export interface BasicS3AuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof BasicS3AuthParamsDTO
     */
    'bucketName'?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicS3AuthParamsDTO
     */
    'bucketRegion'?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicS3AuthParamsDTO
     */
    'accessKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicS3AuthParamsDTO
     */
    'secretKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicS3AuthParamsDTO
     */
    'path'?: string;
}

