/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BigQueryServiceAccountParamsDTO } from './big-query-service-account-params-dto';

/**
 * 
 * @export
 * @interface BigQueryAuthParamsDTO
 */
export interface BigQueryAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof BigQueryAuthParamsDTO
     */
    'projectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof BigQueryAuthParamsDTO
     */
    'datasetLocation'?: string;
    /**
     * 
     * @type {string}
     * @memberof BigQueryAuthParamsDTO
     */
    'refreshToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof BigQueryAuthParamsDTO
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof BigQueryAuthParamsDTO
     */
    'clientSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof BigQueryAuthParamsDTO
     */
    'defaultDataset'?: string;
    /**
     * 
     * @type {BigQueryServiceAccountParamsDTO}
     * @memberof BigQueryAuthParamsDTO
     */
    'serviceAccountParams'?: BigQueryServiceAccountParamsDTO;
}

