/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConnectorInfoResponseDTO
 */
export interface ConnectorInfoResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof ConnectorInfoResponseDTO
     */
    'description'?: string;
    /**
     * The unique identifier associated with the data connector.
     * @type {string}
     * @memberof ConnectorInfoResponseDTO
     */
    'connectorId'?: string;
    /**
     * An identifiable data connector name that is displayed within Visier.
     * @type {string}
     * @memberof ConnectorInfoResponseDTO
     */
    'displayName'?: string;
}

