/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TenantAndCredential } from './tenant-and-credential';

/**
 * 
 * @export
 * @interface Connector
 */
export interface Connector {
    /**
     * The unique identifier associated with the data connector.
     * @type {string}
     * @memberof Connector
     */
    'connectorId'?: string;
    /**
     * A list of analytic tenants and credentials to be assigned to the connector.
     * @type {Array<TenantAndCredential>}
     * @memberof Connector
     */
    'tenants'?: Array<TenantAndCredential>;
}

