/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CopyS3AuthParamsDTO
 */
export interface CopyS3AuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof CopyS3AuthParamsDTO
     */
    'iamRole'?: string;
}

