/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataProviderAuthParamsDTO } from './data-provider-auth-params-dto';
import { DataProviderBasicInformationDTO } from './data-provider-basic-information-dto';
import { DataProviderBasicMetadataDTO } from './data-provider-basic-metadata-dto';

/**
 * 
 * @export
 * @interface DataProviderAuthInformationDTO
 */
export interface DataProviderAuthInformationDTO {
    /**
     * The authentication information for the credential.
     * @type {DataProviderAuthParamsDTO}
     * @memberof DataProviderAuthInformationDTO
     */
    'dataProviderAuthParams'?: DataProviderAuthParamsDTO;
    /**
     * The display name and description for the credential.
     * @type {DataProviderBasicInformationDTO}
     * @memberof DataProviderAuthInformationDTO
     */
    'dataProviderBasicInformation'?: DataProviderBasicInformationDTO;
    /**
     * 
     * @type {DataProviderBasicMetadataDTO}
     * @memberof DataProviderAuthInformationDTO
     */
    'dataProviderMetadata'?: DataProviderBasicMetadataDTO;
}

