/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MapValue } from './map-value';

/**
 * 
 * @export
 * @interface DataLoadRequest
 */
export interface DataLoadRequest {
    /**
     * A form body key that contains a collection of key-value pairs.   **Note:** The only supported key value is `files` and the value is a comma-separated list of file names.  Example:  `\"files\": \"/path/to/file1.zip.gpg,/path/to/another/file.zip.gpg\"`
     * @type {{ [key: string]: MapValue; }}
     * @memberof DataLoadRequest
     */
    'model'?: { [key: string]: MapValue; };
}

