/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AdpAuthParamsDTO } from './adp-auth-params-dto';
import { BambooAuthParamsDTO } from './bamboo-auth-params-dto';
import { BasicS3AuthParamsDTO } from './basic-s3-auth-params-dto';
import { BigQueryAuthParamsDTO } from './big-query-auth-params-dto';
import { CopyS3AuthParamsDTO } from './copy-s3-auth-params-dto';
import { DayforceV2AuthParamsDTO } from './dayforce-v2-auth-params-dto';
import { DimensionsAuthParamsDTO } from './dimensions-auth-params-dto';
import { FusionAuthParamsDTO } from './fusion-auth-params-dto';
import { GongAuthParamsDTO } from './gong-auth-params-dto';
import { GoogleSheetsAuthParamsDTO } from './google-sheets-auth-params-dto';
import { GoogleWorkspaceAuthParamsDTO } from './google-workspace-auth-params-dto';
import { GreenhouseAuthParamsDTO } from './greenhouse-auth-params-dto';
import { IcimsAuthParamsDTO } from './icims-auth-params-dto';
import { InternalS3AuthParamsDTO } from './internal-s3-auth-params-dto';
import { JdbcAuthParamsDTO } from './jdbc-auth-params-dto';
import { JiraAuthParamsDTO } from './jira-auth-params-dto';
import { LeverAuthParamsDTO } from './lever-auth-params-dto';
import { MedalliaAuthParamsDTO } from './medallia-auth-params-dto';
import { Microsoft365AuthParamsDTO } from './microsoft365-auth-params-dto';
import { MySqlAuthParamsDTO } from './my-sql-auth-params-dto';
import { NamelyAuthParamsDTO } from './namely-auth-params-dto';
import { OracleDbAuthParamsDTO } from './oracle-db-auth-params-dto';
import { QualtricsAuthParamsDTO } from './qualtrics-auth-params-dto';
import { RedshiftAuthParamsDTO } from './redshift-auth-params-dto';
import { SalesforceAuthParamsDTO } from './salesforce-auth-params-dto';
import { SalesforceV2AuthParamsDTO } from './salesforce-v2-auth-params-dto';
import { ServiceNowAuthParamsDTO } from './service-now-auth-params-dto';
import { SlackAuthParamsDTO } from './slack-auth-params-dto';
import { SnowflakeAuthParamsDTO } from './snowflake-auth-params-dto';
import { SqlServerAuthParamsDTO } from './sql-server-auth-params-dto';
import { SuccessFactorsAuthParamsDTO } from './success-factors-auth-params-dto';
import { UltimateAuthParamsDTO } from './ultimate-auth-params-dto';
import { WillowAuthParamsDTO } from './willow-auth-params-dto';
import { WorkdayAuthParamsDTO } from './workday-auth-params-dto';
import { WorkdayRaasAuthParamsDTO } from './workday-raas-auth-params-dto';
import { ZoomAuthParamsDTO } from './zoom-auth-params-dto';

/**
 * 
 * @export
 * @interface DataProviderAuthParamsDTO
 */
export interface DataProviderAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof DataProviderAuthParamsDTO
     */
    'tenantDomainName'?: string;
    /**
     * The data provider associated with the credential.  - Valid values: UKG, Dimensions, Workday, Redshift, BasicS3, CopyS3, SqlServer, Snowflake
     * @type {string}
     * @memberof DataProviderAuthParamsDTO
     */
    'provider'?: DataProviderAuthParamsDTOProviderEnum;
    /**
     * 
     * @type {BambooAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'bambooAuthParams'?: BambooAuthParamsDTO;
    /**
     * 
     * @type {GreenhouseAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'greenhouseAuthParams'?: GreenhouseAuthParamsDTO;
    /**
     * 
     * @type {GoogleSheetsAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'googleSheetsAuthParams'?: GoogleSheetsAuthParamsDTO;
    /**
     * 
     * @type {JiraAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'jiraAuthParams'?: JiraAuthParamsDTO;
    /**
     * 
     * @type {LeverAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'leverAuthParams'?: LeverAuthParamsDTO;
    /**
     * 
     * @type {NamelyAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'namelyAuthParams'?: NamelyAuthParamsDTO;
    /**
     * 
     * @type {QualtricsAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'qualtricsAuthParams'?: QualtricsAuthParamsDTO;
    /**
     * 
     * @type {SalesforceAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'salesforceAuthParams'?: SalesforceAuthParamsDTO;
    /**
     * 
     * @type {UltimateAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'ultimateAuthParams'?: UltimateAuthParamsDTO;
    /**
     * 
     * @type {WorkdayAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'workdayAuthParams'?: WorkdayAuthParamsDTO;
    /**
     * 
     * @type {IcimsAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'icimsAuthParams'?: IcimsAuthParamsDTO;
    /**
     * 
     * @type {ServiceNowAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'serviceNowAuthParams'?: ServiceNowAuthParamsDTO;
    /**
     * 
     * @type {JdbcAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'jdbcAuthParams'?: JdbcAuthParamsDTO;
    /**
     * 
     * @type {BasicS3AuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    's3AuthParams'?: BasicS3AuthParamsDTO;
    /**
     * 
     * @type {InternalS3AuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'internalS3AuthParams'?: InternalS3AuthParamsDTO;
    /**
     * 
     * @type {CopyS3AuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'copyS3AuthParams'?: CopyS3AuthParamsDTO;
    /**
     * 
     * @type {RedshiftAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'redshiftAuthParams'?: RedshiftAuthParamsDTO;
    /**
     * 
     * @type {SnowflakeAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'snowflakeAuthParams'?: SnowflakeAuthParamsDTO;
    /**
     * 
     * @type {BigQueryAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'bigQueryAuthParams'?: BigQueryAuthParamsDTO;
    /**
     * 
     * @type {SqlServerAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'sqlServerAuthParams'?: SqlServerAuthParamsDTO;
    /**
     * 
     * @type {DimensionsAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'dimensionsAuthParams'?: DimensionsAuthParamsDTO;
    /**
     * 
     * @type {WillowAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'willowAuthParams'?: WillowAuthParamsDTO;
    /**
     * 
     * @type {object}
     * @memberof DataProviderAuthParamsDTO
     */
    'emptyAuthParams'?: object;
    /**
     * 
     * @type {SuccessFactorsAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'successFactorsAuthParams'?: SuccessFactorsAuthParamsDTO;
    /**
     * 
     * @type {FusionAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'fusionAuthParams'?: FusionAuthParamsDTO;
    /**
     * 
     * @type {AdpAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'adpAuthParams'?: AdpAuthParamsDTO;
    /**
     * 
     * @type {MedalliaAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'medalliaAuthParams'?: MedalliaAuthParamsDTO;
    /**
     * 
     * @type {SalesforceV2AuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'salesforceV2AuthParams'?: SalesforceV2AuthParamsDTO;
    /**
     * 
     * @type {GongAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'gongAuthParams'?: GongAuthParamsDTO;
    /**
     * 
     * @type {ZoomAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'zoomAuthParams'?: ZoomAuthParamsDTO;
    /**
     * 
     * @type {DayforceV2AuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'dayforceV2AuthParams'?: DayforceV2AuthParamsDTO;
    /**
     * 
     * @type {SlackAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'slackAuthParams'?: SlackAuthParamsDTO;
    /**
     * 
     * @type {MySqlAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'mySqlAuthParams'?: MySqlAuthParamsDTO;
    /**
     * 
     * @type {WorkdayRaasAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'workdayRaasAuthParams'?: WorkdayRaasAuthParamsDTO;
    /**
     * 
     * @type {Microsoft365AuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'ms365AuthParams'?: Microsoft365AuthParamsDTO;
    /**
     * 
     * @type {GoogleWorkspaceAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'googleWorkspaceAuthParams'?: GoogleWorkspaceAuthParamsDTO;
    /**
     * 
     * @type {OracleDbAuthParamsDTO}
     * @memberof DataProviderAuthParamsDTO
     */
    'oracleDbAuthParams'?: OracleDbAuthParamsDTO;
    /**
     * 
     * @type {boolean}
     * @memberof DataProviderAuthParamsDTO
     */
    'hasUpdates'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DataProviderAuthParamsDTO
     */
    'authContext'?: DataProviderAuthParamsDTOAuthContextEnum;
}

type DataProviderAuthParamsDTOProviderEnum = 'Bamboo' | 'GoogleSheets' | 'Greenhouse' | 'Jira' | 'Lever' | 'Namely' | 'Qualtrics' | 'Salesforce' | 'UKG' | 'Workday' | 'Icims' | 'ServiceNow' | 'Jdbc' | 'BasicS3' | 'InternalS3' | 'CopyS3' | 'Redshift' | 'Snowflake' | 'BigQuery' | 'SqlServer' | 'Dimensions' | 'IcimsPartnerProviderRedshift' | 'Willow' | 'SuccessFactors' | 'IcimsV2' | 'ADP' | 'WorkdayV2' | 'ServiceNowV2' | 'Medallia' | 'Fusion' | 'SalesforceV2' | 'Gong' | 'Zoom' | 'GoogleCalendar' | 'UKGV2' | 'DayforceV2' | 'GoogleActivityReport' | 'Slack' | 'MySql' | 'WorkdayRaas' | 'Microsoft365' | 'GoogleWorkspace' | 'OracleDb' | 'SmartRecruiters'
type DataProviderAuthParamsDTOAuthContextEnum = 'DefaultDataExtraction' | 'WorkplaceDynamicsDataExtraction' | 'Notification'


