/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DayforceV2AuthParamsDTO
 */
export interface DayforceV2AuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof DayforceV2AuthParamsDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof DayforceV2AuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof DayforceV2AuthParamsDTO
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DayforceV2AuthParamsDTO
     */
    'tokenHost'?: string;
    /**
     * 
     * @type {string}
     * @memberof DayforceV2AuthParamsDTO
     */
    'hostDomainName'?: string;
}

