/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DimensionsAuthParamsDTO
 */
export interface DimensionsAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof DimensionsAuthParamsDTO
     */
    'appKey'?: string;
    /**
     * 
     * @type {string}
     * @memberof DimensionsAuthParamsDTO
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DimensionsAuthParamsDTO
     */
    'clientSecret'?: string;
    /**
     * 
     * @type {string}
     * @memberof DimensionsAuthParamsDTO
     */
    'vanityUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof DimensionsAuthParamsDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof DimensionsAuthParamsDTO
     */
    'password'?: string;
}

