/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataVersionObject } from './data-version-object';

/**
 * 
 * @export
 * @interface DisableDVModel
 */
export interface DisableDVModel {
    /**
     * A list of objects representing the data version to disable for a particular analytic tenant.  The limit of objects to include per request is 1000.
     * @type {Array<DataVersionObject>}
     * @memberof DisableDVModel
     */
    'dataVersionObjects'?: Array<DataVersionObject>;
}

