/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisableDVModel } from './disable-dvmodel';

/**
 * 
 * @export
 * @interface DisableDVRequest
 */
export interface DisableDVRequest {
    /**
     * A form body key that contains a collection of key-value pairs.
     * @type {DisableDVModel}
     * @memberof DisableDVRequest
     */
    'model'?: DisableDVModel;
}

