/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Result } from './result';

/**
 * 
 * @export
 * @interface DisableDVResponse
 */
export interface DisableDVResponse {
    /**
     * The number of data versions that failed during the disabling process.
     * @type {number}
     * @memberof DisableDVResponse
     */
    'totalFailures'?: number;
    /**
     * The number of data versions that were disabled successfully.
     * @type {number}
     * @memberof DisableDVResponse
     */
    'totalSuccess'?: number;
    /**
     * A list of objects representing the disabling process.
     * @type {Array<Result>}
     * @memberof DisableDVResponse
     */
    'results'?: Array<Result>;
}

