/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DispatchingJobStatusResponse
 */
export interface DispatchingJobStatusResponse {
    /**
     * The ID of the dispatching job that generated the extraction jobs.
     * @type {string}
     * @memberof DispatchingJobStatusResponse
     */
    'jobId'?: string;
    /**
     * The tenant that owns the dispatching job. This is usually the administrating tenant.
     * @type {string}
     * @memberof DispatchingJobStatusResponse
     */
    'tenantCode'?: string;
    /**
     * The current state of the job.
     * @type {string}
     * @memberof DispatchingJobStatusResponse
     */
    'status'?: string;
    /**
     * The number of extraction jobs that were generated by the dispatching job.
     * @type {number}
     * @memberof DispatchingJobStatusResponse
     */
    'totalJobsDispatched'?: number;
}

