/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UploadToExcludeModel } from './upload-to-exclude-model';

/**
 * 
 * @export
 * @interface ExcludeDataUploadsRequest
 */
export interface ExcludeDataUploadsRequest {
    /**
     * A form body key that contains a collection of key-value pairs.
     * @type {UploadToExcludeModel}
     * @memberof ExcludeDataUploadsRequest
     */
    'model'?: UploadToExcludeModel;
}

