/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtractorCredentialAPIDTO } from './extractor-credential-apidto';

/**
 * 
 * @export
 * @interface ExtractorCredentialsAPIDTO
 */
export interface ExtractorCredentialsAPIDTO {
    /**
     * A list of objects representing all the available connector credentials in Production.
     * @type {Array<ExtractorCredentialAPIDTO>}
     * @memberof ExtractorCredentialsAPIDTO
     */
    'connectorCredentials'?: Array<ExtractorCredentialAPIDTO>;
    /**
     * The number of connector credentials to return. The maximum number of data connector credentials to return is 1000.
     * @type {number}
     * @memberof ExtractorCredentialsAPIDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving values from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof ExtractorCredentialsAPIDTO
     */
    'start'?: number;
}

