/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExtractorCredentialAPIDTO
 */
export interface ExtractorCredentialAPIDTO {
    /**
     * The ID associated with the connector credential.
     * @type {string}
     * @memberof ExtractorCredentialAPIDTO
     */
    'credentialId'?: string;
    /**
     * An identifiable connector credential name that is displayed within Visier.
     * @type {string}
     * @memberof ExtractorCredentialAPIDTO
     */
    'displayName'?: string;
    /**
     * The data provider associated with the credential.
     * @type {string}
     * @memberof ExtractorCredentialAPIDTO
     */
    'dataProvider'?: string;
    /**
     * Whether this credential is inherited from another tenant.
     * @type {boolean}
     * @memberof ExtractorCredentialAPIDTO
     */
    'isInherited'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ExtractorCredentialAPIDTO
     */
    'authContext'?: string;
}

