/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExtractionJob } from './extraction-job';

/**
 * 
 * @export
 * @interface ExtractionJobAndStatusResponse
 */
export interface ExtractionJobAndStatusResponse {
    /**
     * The ID of the dispatching job that generated the extraction jobs.
     * @type {string}
     * @memberof ExtractionJobAndStatusResponse
     */
    'parentJobId'?: string;
    /**
     * The tenant that owns the dispatching job. This is usually the administrating tenant.
     * @type {string}
     * @memberof ExtractionJobAndStatusResponse
     */
    'parentTenantCode'?: string;
    /**
     * The number of extraction jobs to return. The maximum number of jobs to return is 1000.
     * @type {number}
     * @memberof ExtractionJobAndStatusResponse
     */
    'limit'?: number;
    /**
     * The index to start retrieving results from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof ExtractionJobAndStatusResponse
     */
    'start'?: number;
    /**
     * A list of extraction job information.
     * @type {Array<ExtractionJob>}
     * @memberof ExtractionJobAndStatusResponse
     */
    'extractionJobs'?: Array<ExtractionJob>;
}

