/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GongAuthParamsDTO
 */
export interface GongAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof GongAuthParamsDTO
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GongAuthParamsDTO
     */
    'clientSecret'?: string;
}

