/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ImportDefinitionAPIDTO } from './import-definition-apidto';

/**
 * 
 * @export
 * @interface ImportDefinitionsAPIDTO
 */
export interface ImportDefinitionsAPIDTO {
    /**
     * A list of objects representing all the available data connectors in Production.
     * @type {Array<ImportDefinitionAPIDTO>}
     * @memberof ImportDefinitionsAPIDTO
     */
    'dataConnectors'?: Array<ImportDefinitionAPIDTO>;
    /**
     * The number of data connectors to return. The maximum number of data connectors to return is 1000.
     * @type {number}
     * @memberof ImportDefinitionsAPIDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving values from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof ImportDefinitionsAPIDTO
     */
    'start'?: number;
}

