/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ImportDefinitionAPIDTO
 */
export interface ImportDefinitionAPIDTO {
    /**
     * The ID associated with the data connector.
     * @type {string}
     * @memberof ImportDefinitionAPIDTO
     */
    'connectorId'?: string;
    /**
     * An identifiable data connector name that is displayed within Visier.
     * @type {string}
     * @memberof ImportDefinitionAPIDTO
     */
    'displayName'?: string;
    /**
     * The ID associated with the connector credentials currently assigned to this data connector.
     * @type {string}
     * @memberof ImportDefinitionAPIDTO
     */
    'credentialId'?: string;
}

