/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UploadToIncludeModel } from './upload-to-include-model';

/**
 * 
 * @export
 * @interface IncludeDataUploadsRequest
 */
export interface IncludeDataUploadsRequest {
    /**
     * A form body key that contains a collection of key-value pairs.
     * @type {UploadToIncludeModel}
     * @memberof IncludeDataUploadsRequest
     */
    'model'?: UploadToIncludeModel;
}

