/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InternalS3AuthParamsDTO
 */
export interface InternalS3AuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof InternalS3AuthParamsDTO
     */
    'bucketName'?: string;
    /**
     * 
     * @type {string}
     * @memberof InternalS3AuthParamsDTO
     */
    'path'?: string;
}

