/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JiraConnectParamsDTO } from './jira-connect-params-dto';

/**
 * 
 * @export
 * @interface JiraAuthParamsDTO
 */
export interface JiraAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof JiraAuthParamsDTO
     */
    'apiToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof JiraAuthParamsDTO
     */
    'hostName'?: string;
    /**
     * 
     * @type {JiraConnectParamsDTO}
     * @memberof JiraAuthParamsDTO
     */
    'connectParams'?: JiraConnectParamsDTO;
}

