/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MapValue
 */
export interface MapValue {
    /**
     * A comma-separated list of encrypted, compressed batch filenames to be processed.
     * @type {Array<string>}
     * @memberof MapValue
     */
    'value'?: Array<string>;
}

