/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MedalliaAuthParamsDTO
 */
export interface MedalliaAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof MedalliaAuthParamsDTO
     */
    'tenantDomainName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MedalliaAuthParamsDTO
     */
    'instanceUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof MedalliaAuthParamsDTO
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MedalliaAuthParamsDTO
     */
    'clientSecret'?: string;
}

