/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Microsoft365AuthParamsDTO
 */
export interface Microsoft365AuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof Microsoft365AuthParamsDTO
     */
    'oAuthTenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Microsoft365AuthParamsDTO
     */
    'clientId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Microsoft365AuthParamsDTO
     */
    'clientSecret'?: string;
}

