/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MultipleTenantDataVersionsDetailsDTO } from './multiple-tenant-data-versions-details-dto';

/**
 * 
 * @export
 * @interface MultipleTenantDataVersionsListDTO
 */
export interface MultipleTenantDataVersionsListDTO {
    /**
     * A list of analytic tenants and their latest enabled data versions.
     * @type {Array<MultipleTenantDataVersionsDetailsDTO>}
     * @memberof MultipleTenantDataVersionsListDTO
     */
    'tenants'?: Array<MultipleTenantDataVersionsDetailsDTO>;
    /**
     * The number of analytic tenants to retrieve. The maximum number to retrieve is 1000.
     * @type {number}
     * @memberof MultipleTenantDataVersionsListDTO
     */
    'limit'?: number;
    /**
     * The index to start retrieving results from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof MultipleTenantDataVersionsListDTO
     */
    'start'?: number;
}

