/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataVersionAndDateDTO } from './data-version-and-date-dto';

/**
 * 
 * @export
 * @interface MultipleTenantDataVersionsDetailsDTO
 */
export interface MultipleTenantDataVersionsDetailsDTO {
    /**
     * The owner of the data versions.
     * @type {string}
     * @memberof MultipleTenantDataVersionsDetailsDTO
     */
    'tenantCode'?: string;
    /**
     * The latest enabled data versions for the given analytic tenant. If the analytic tenant  has no enabled data versions, an empty string \"\" is returned.
     * @type {Array<DataVersionAndDateDTO>}
     * @memberof MultipleTenantDataVersionsDetailsDTO
     */
    'dataVersions'?: Array<DataVersionAndDateDTO>;
}

