/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OracleDbAuthParamsDTO
 */
export interface OracleDbAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof OracleDbAuthParamsDTO
     */
    'host'?: string;
    /**
     * 
     * @type {string}
     * @memberof OracleDbAuthParamsDTO
     */
    'port'?: string;
    /**
     * 
     * @type {string}
     * @memberof OracleDbAuthParamsDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof OracleDbAuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof OracleDbAuthParamsDTO
     */
    'serviceName'?: string;
}

