/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProcessingJob } from './processing-job';

/**
 * 
 * @export
 * @interface ProcessingJobStatusResponse
 */
export interface ProcessingJobStatusResponse {
    /**
     * The job ID of the receiving job that spawned this job
     * @type {string}
     * @memberof ProcessingJobStatusResponse
     */
    'parentJobId'?: string;
    /**
     * The tenant code of the receiving job that spawned this job.
     * @type {string}
     * @memberof ProcessingJobStatusResponse
     */
    'parentTenantCode'?: string;
    /**
     * The limit of processing jobs to retrieve per page.
     * @type {number}
     * @memberof ProcessingJobStatusResponse
     */
    'limit'?: number;
    /**
     * The index to start retrieving results from, also known as offset. The index begins at 0.
     * @type {number}
     * @memberof ProcessingJobStatusResponse
     */
    'start'?: number;
    /**
     * A list of objects representing the processing jobs to retrieve.
     * @type {Array<ProcessingJob>}
     * @memberof ProcessingJobStatusResponse
     */
    'processingJobs'?: Array<ProcessingJob>;
}

