/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReceivingJob
 */
export interface ReceivingJob {
    /**
     * The job ID of the receiving job for the analytic tenant.
     * @type {string}
     * @memberof ReceivingJob
     */
    'receivingJobId'?: string;
    /**
     * The analytic tenant code.
     * @type {string}
     * @memberof ReceivingJob
     */
    'tenantCode'?: string;
    /**
     * The status of the receiving job for the analytic tenant.
     * @type {string}
     * @memberof ReceivingJob
     */
    'status'?: string;
}

