/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RedshiftAuthParamsDTO
 */
export interface RedshiftAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'endpoint'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'port'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'database'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'tablePrefix'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedshiftAuthParamsDTO
     */
    'schema'?: string;
}

