/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SnowflakeAuthParamsDTO
 */
export interface SnowflakeAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'accountIdentifier'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'database'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'schema'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'warehouse'?: string;
    /**
     * 
     * @type {string}
     * @memberof SnowflakeAuthParamsDTO
     */
    'privateKey'?: string;
}

