/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SqlServerAuthParamsDTO
 */
export interface SqlServerAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof SqlServerAuthParamsDTO
     */
    'host'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqlServerAuthParamsDTO
     */
    'port'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqlServerAuthParamsDTO
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqlServerAuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof SqlServerAuthParamsDTO
     */
    'database'?: string;
}

