/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StartExtractionModel
 */
export interface StartExtractionModel {
    /**
     * A list of analytic tenants to dispatch extraction jobs for. One extraction job is dispatched per tenant.
     * @type {Array<string>}
     * @memberof StartExtractionModel
     */
    'tenants'?: Array<string>;
    /**
     * If \"true\", one extraction job is dispatched for each accessible analytic tenant.
     * @type {boolean}
     * @memberof StartExtractionModel
     */
    'allTenants'?: boolean;
    /**
     * The time from which to extract data.
     * @type {string}
     * @memberof StartExtractionModel
     */
    'overrideLastExtractionTimestamp'?: string;
    /**
     * If \"true\", the generated data load artifacts are published to Production immediately.
     * @type {boolean}
     * @memberof StartExtractionModel
     */
    'publishDataLoadArtifacts'?: boolean;
    /**
     * If \"true\", a processing job is spawned after a dispatched extraction job runs successfully.
     * @type {boolean}
     * @memberof StartExtractionModel
     */
    'runProcessingJob'?: boolean;
    /**
     * The unique identifier of the data category on which to trigger the extraction job.
     * @type {string}
     * @memberof StartExtractionModel
     */
    'dataCategoryId'?: string;
    /**
     * If \"true\", the job does not generate data load artifacts. If unspecified, the default is \"false\".
     * @type {boolean}
     * @memberof StartExtractionModel
     */
    'disableArtifactGeneration'?: boolean;
}

