/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SubjectMissingAccessDTO
 */
export interface SubjectMissingAccessDTO {
    /**
     * The subjects that cannot be accessed.
     * @type {string}
     * @memberof SubjectMissingAccessDTO
     */
    'subject'?: SubjectMissingAccessDTOSubjectEnum;
    /**
     * The attributes that cannot be accessed.
     * @type {Array<string>}
     * @memberof SubjectMissingAccessDTO
     */
    'attributes'?: Array<string>;
}

type SubjectMissingAccessDTOSubjectEnum = 'Employee' | 'Employee_Budgeted_Compensation' | 'Employment_Start' | 'Employment_Exit' | 'Absenteeism' | 'Supervisory' | 'Organization' | 'Compensation_Payout' | 'CustomSubject' | 'TestConnectionSubject' | 'Internal_Placement' | 'Pay_Change' | 'Hire' | 'Applicant' | 'Candidate' | 'Requisition'


