/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TenantAndCredential
 */
export interface TenantAndCredential {
    /**
     * The unique identifier associated with the tenant.
     * @type {string}
     * @memberof TenantAndCredential
     */
    'tenantCode'?: string;
    /**
     * The unique identifier associated with the credential.
     * @type {string}
     * @memberof TenantAndCredential
     */
    'credentialId'?: string;
}

