/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TenantDataUploadStatusResponseDTO } from './tenant-data-upload-status-response-dto';

/**
 * 
 * @export
 * @interface TenantDataUploadsResponseDTO
 */
export interface TenantDataUploadsResponseDTO {
    /**
     * The tenant code of the analytic tenant owning the data uploads.
     * @type {string}
     * @memberof TenantDataUploadsResponseDTO
     */
    'tenantCode'?: string;
    /**
     * The data uploads completed for the specified analytic tenant. The list is empty if no previous data uploads are found for the analytic tenant.
     * @type {Array<TenantDataUploadStatusResponseDTO>}
     * @memberof TenantDataUploadsResponseDTO
     */
    'uploads'?: Array<TenantDataUploadStatusResponseDTO>;
}

