/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TenantDataUploadStatusResponseDTO
 */
export interface TenantDataUploadStatusResponseDTO {
    /**
     * The upload time of the data upload.
     * @type {string}
     * @memberof TenantDataUploadStatusResponseDTO
     */
    'uploadTime'?: string;
    /**
     * If \"true\", the data upload is included.
     * @type {boolean}
     * @memberof TenantDataUploadStatusResponseDTO
     */
    'included'?: boolean;
}

