/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UploadToExclude } from './upload-to-exclude';

/**
 * 
 * @export
 * @interface UploadToExcludeModel
 */
export interface UploadToExcludeModel {
    /**
     * A list of objects representing the data uploads to exclude for a particular analytic tenant.
     * @type {Array<UploadToExclude>}
     * @memberof UploadToExcludeModel
     */
    'uploads'?: Array<UploadToExclude>;
}

