/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UploadToInclude } from './upload-to-include';

/**
 * 
 * @export
 * @interface UploadToIncludeModel
 */
export interface UploadToIncludeModel {
    /**
     * A list of objects representing the data uploads to include for a particular analytic tenant.
     * @type {Array<UploadToInclude>}
     * @memberof UploadToIncludeModel
     */
    'uploads'?: Array<UploadToInclude>;
}

