/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UploadToExclude
 */
export interface UploadToExclude {
    /**
     * The tenant code of the analytic tenant you are excluding a data upload for.
     * @type {string}
     * @memberof UploadToExclude
     */
    'tenantCode'?: string;
    /**
     * If \"true\", all data uploads are excluded for the analytic tenant.
     * @type {boolean}
     * @memberof UploadToExclude
     */
    'excludeAll'?: boolean;
    /**
     * A comma-separated list of strings representing the upload time of each data upload to exclude.
     * @type {Array<string>}
     * @memberof UploadToExclude
     */
    'uploadTimes'?: Array<string>;
}

