/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkdayAuthParamsDTO
 */
export interface WorkdayAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof WorkdayAuthParamsDTO
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayAuthParamsDTO
     */
    'domainName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayAuthParamsDTO
     */
    'implementationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayAuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayAuthParamsDTO
     */
    'integrationSystemId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayAuthParamsDTO
     */
    'apiKey'?: string;
}

