/*
Visier Data and Job Handling APIs

Visier APIs for data and job handling

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WorkdayRaasAuthParamsDTO
 */
export interface WorkdayRaasAuthParamsDTO {
    /**
     * 
     * @type {string}
     * @memberof WorkdayRaasAuthParamsDTO
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayRaasAuthParamsDTO
     */
    'domainName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayRaasAuthParamsDTO
     */
    'implementationName'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayRaasAuthParamsDTO
     */
    'password'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkdayRaasAuthParamsDTO
     */
    'testReportUrl'?: string;
}

